---
title: "Homework7"
author: "Tracie-Lynn Lamoreux, Macy Schanbacher, Nic Rhoads"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggmosaic)
HAPPY<- readRDS("Happy.rds")
```

Cleaning:
```{r}
HAPPY[HAPPY == "DK" | HAPPY == "IAP" | HAPPY == "NA"] <- NA
HAPPY$AGE[HAPPY$AGE == "89 OR OLDER"] <-89
str(HAPPY)
```

Casting columns:
```{r}
HAPPY$HAPPY <- as.factor(HAPPY$HAPPY)
HAPPY$YEAR <- as.numeric(HAPPY$YEAR)
HAPPY$AGE <- as.numeric(HAPPY$AGE)
HAPPY$SEX <- as.factor(HAPPY$SEX)
HAPPY$MARITAL <- as.factor(HAPPY$MARITAL)
HAPPY$DEGREE <- as.factor(HAPPY$DEGREE)
HAPPY$FINRELA <- as.factor(HAPPY$FINRELA)
HAPPY$HEALTH <- as.factor(HAPPY$HEALTH)
HAPPY$PARTYID <- as.factor(HAPPY$PARTYID)
HAPPY$POLVIEWS <- as.factor(HAPPY$POLVIEWS)
```

Re-ordering levels:
```{r}
HAPPY$DEGREE <- factor(HAPPY$DEGREE, levels = levels(reorder(HAPPY$DEGREE, HAPPY$AGE, na.rm = TRUE)))
HAPPY$MARITAL <- factor(HAPPY$MARITAL, levels = levels(reorder(HAPPY$MARITAL, HAPPY$AGE, na.rm = TRUE)))
HAPPY$HAPPY <- factor(HAPPY$HAPPY, levels = c("NOT TOO HAPPY", "PRETTY HAPPY", "VERY HAPPY"))
HAPPY$FINRELA <- factor(HAPPY$FINRELA, levels = c("FAR BELOW AVERAGE", "BELOW AVERAGE", "AVERAGE","ABOVE AVERAGE", "FAR ABOVE AVERAGE"))
HAPPY$HEALTH <- factor(HAPPY$HEALTH, levels = c("POOR", "FAIR", "GOOD", "EXCELLENT"))
```

Tracie-Lynn's question:
```{r}
ggplot(data = HAPPY) + geom_mosaic(aes(x = product(MARITAL), fill = HAPPY, weight = 1), na.rm = TRUE)+ facet_wrap(HAPPY$HEALTH) + theme_classic()

```
Tracie-Lynn decided to investigate the relationship of happiness, marital status, and health. It seems like a 
lot more people are happy if they are in better health and married as opposed to poor health and never married married. 
Macy's question:
```{r}

```

Nic's question:
```{r}
ggplot(data = HAPPY) + geom_mosaic(aes(x = product(MARITAL), fill = HAPPY, weight = 1), na.rm = TRUE) + facet_wrap(HAPPY$SEX)
```
